pipeline {
    agent { 
        dockerfile {
            filename './Task4/Docker/apache/Dockerfile'
            args '-u root:sudo'
        } 
        
    }
    stages {
        stage('Update repo list') {
            steps {
                sh 'apt update -y'
            }
        }
        stage('Test') {
            steps {
                sh 'python3 --version'
            }
        }
    }
}
