---
- name: Install Zabbix Client
  hosts: zabbix_client
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Install a .deb package
      apt:
        deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
        state: present

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
       update_cache: yes

    - name: install zabbix-agent
      apt:
        name: zabbix-agent
        state: present

    - name: config zabbix-agent
      template:
        src: /home/ubuntu/zabbix_agent2.conf.j2
        dest: /etc/zabbix/zabbix_agent2.conf
        owner: root
        group: root
        mode: 644
      notify: restart zabbix-agent

    - name: start zabbix-agent
      service:
        name: zabbix-agent
        state: started

  handlers:
    - name: restart zabbix-agent
      service:
        name: zabbix-agent
        state: restarted
