---
ansible_user                 : ubuntu
ansible_connection           : ssh
ansible_ssh_private_key_file : /home/ubuntu/.ssh/id_rsa
ansible_sudo_pass            : "{{PASS}}"
zabbix_server                : 172.31.25.0
