---
- name: Copy project
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: daemon.json, dest: /etc/docker/daemon.json, mode: 0644 }
    - { src: docker, dest: /etc/default/docker, mode: 0644 }
    - { src: docker.service, dest: "/lib/systemd/system/", mode: 0644 }

- name: Reload daemons
  systemd:
    daemon_reload: yes

- name: Restart docker 
  service:
    name: docker
    state: restarted